# templates/pdb.yaml
# ============================================================
# Observer PodDisruptionBudget
# ============================================================
{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "observer.fullname" . }}
  labels:
    {{- include "observer.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "observer.selectorLabels" . | nindent 6 }}
{{- end }}
