# templates/pdb.yaml
# ============================================================
# QTS PodDisruptionBudget
# ============================================================
{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "qts.fullname" . }}
  labels:
    {{- include "qts.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "qts.selectorLabels" . | nindent 6 }}
{{- end }}
