# n8n ArgoCD Application (OCI #2 클러스터)
# ============================================================
# OCI #2 서버에 n8n 워크플로우 자동화 플랫폼을 배포
# 감시자(n8n)와 감시 대상(QTS/Observer)은 별도 서버에서 운영
# ============================================================
# TODO: <OCI_2_K3S_API_주소>를 OCI #2의 K3s API 서버 주소로 변경
#       (argocd cluster add 명령으로 멀티 클러스터 등록 후 설정)
# ============================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/instance: n8n-oci2
    app.kubernetes.io/part-of: tawbury-platform
spec:
  project: default

  source:
    repoURL: https://github.com/tawbury/Deployment.git
    targetRevision: main
    path: clusters/oci-2/n8n/helm-charts
    helm:
      valueFiles:
        - values.yaml
        - values.oci.yaml

  destination:
    # TODO: OCI #2 K3s API 서버 주소로 변경 (멀티 클러스터 등록 후)
    # 등록 방법: argocd cluster add <CONTEXT_NAME> --name oci-2
    server: https://<OCI_2_K3S_API_주소>:6443
    namespace: n8n

  syncPolicy:
    # 현재는 수동 동기화 (모니터링만)
    # 안정화 후 자동 동기화 활성화:
    #   automated:
    #     prune: true
    #     selfHeal: true
    syncOptions:
      - CreateNamespace=true
