# QTS Production ArgoCD Application
# ============================================================
# Deploys QTS (Quant Trading System) to observer-prod namespace
# alongside Observer for shared PostgreSQL and data access
# ============================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qts-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: qts
    app.kubernetes.io/instance: qts-prod
    app.kubernetes.io/part-of: tawbury-platform
spec:
  project: tawbury-platform

  source:
    repoURL: https://github.com/tawbury/Deployment
    targetRevision: HEAD
    path: clusters/oci-1/qts
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: observer-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health check customization
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
